### ISSUE TITLE
bad code

### ISSUE THREAD

**Issue by Rires-Magica** [Favreyo/untisfd#1]
use java instead of csharp

**Comment by stilllogic20** [comment]
I think so too.

**Comment by Rires-Magica** [comment]
japanese junior high school english skill

**Comment by stilllogic20** [comment]
yup truancy

**Comment by Favreyo** [comment]
334 yattaze toukousha shotbow network

**Comment by stilllogic20** [comment]
334 yattaze toukousha shotbow network

**Comment by Favreyo** [comment]
これstreamなんだな

**Comment by stilllogic20** [comment]
?

**Comment by Favreyo** [comment]
issueから異臭がするcv @stilllogic20

**Comment by stilllogic20** [comment]
smell

**Comment by stilllogic20** [comment]
dirty code tournament no.1

**Comment by underecho** [comment]
pls close Fuckin' issue
